### ISSUE TITLE
Loading Iconify plug-in...

### ISSUE THREAD

**Issue by Whatsupcory** [iconify/iconify-figma#10] opened 2019-10-29 17:37 UTC
Is there any way to get past this? The plug-in stopped loading. I love your plug-in and used it a lot. 

https://share.getcloudapp.com/5zu5nBw6

https://share.getcloudapp.com/mXu7JpJX

**Comment by cyberalien** [comment] 2019-10-29 17:43
Its a mystery issue that I'm unable to replicate or debug. Seems to affect few people. See https://github.com/iconify/iconify-figma/issues/6

It should not be happening at all. That file is loaded from CloudFlare, which is reliable and not known to have such bugs.

**Comment by cyberalien** [comment] 2019-10-29 17:45
Closing as duplicate of https://github.com/iconify/iconify-figma/issues/6

If you'll find what is causing it, please do post on linked issue. Unfortunately I'm unable to help because it is not an issue with Iconify. I think issue is either at your computer or in Cloudflare or a weird browser bug.

**Closed by cyberalien** 2019-10-29 17:45 UTC
